### ISSUE TITLE
Review card for 2018-09-11 CNX Release

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx#12]
## Milestone dates:
- Code freeze (no new features): **2018-08-30**
- Code deployed to staging server: 2018-08-31
- Testing on staging server: 2018-09-04 (Tues. after Labor Day) => 2018-09-07
- RC Review meeting: 2018-09-04
- Code Released to Production: **2018-09-11**

## Link to release report
https://app.zenhub.com/workspace/o/connexions/cnx/reports?report=release&release=5b71ea2f34a8997d22bf0f59

## Repos updated:
- oer.exports Queued.quadcopter v0.62.0
- webview v0.36.2
- cnx-recipes v1.14.0
- Products.RhaptosPrint v0.130
- cnx-press 5.0.0
- nebuchadnezzar 5.1.0
- cnx-litezip (press dependency) 1.4.0
- cnxml (press dependency) v2.2.0
- cnx-archive 4.3.2
- cnx-db 2.3.4

## [Demo](https://app.zenhub.com/workspace/o/connexions/cnx/boards?labels=rc%3Ademo&milestones=CNX%20Q3%232018-09-30&releases=5b71ea2f34a8997d22bf0f59&repos=137909279,132146582,11369603,54509938,47001649,52555418,16184890,69261380,73113116,17912002,49744755,69270352,56601849,96546820,17381641,73112925,4727655,2917192,69508046,11369724):
- click "Demo" above to see issues w/ label `rc:demo`

## Repo Checklist (Books+CNX)
<details><summary>Click to expand checklist</summary>

- [x] **oer.exports** (*Helene*)
	- [x] https://github.com/Connexions/oer.exports/blob/master/version.txt should match current release
	- [x] Release created in https://github.com/Connexions/oer.exports/releases
	- [x] New RhaptosPrint egg should be built by DevOps (they need the version number)
- [x] **cnx-recipes** (*Helene*)
	- [x] Release created in https://github.com/Connexions/cnx-recipes/releases
	- [x] PyPi version revved
	- [x] cnx-deploy: `environments/__prod_envs/files/publishing-requirements.txt` should be updated -- a bot will automatically create this PR, which will need to be reviewed and merged.
- [x] **webview** (*Helene*)
 	- [x] Release created in https://github.com/Connexions/webview/releases
	- [x] Tarball for version needs to be available at https://packages.cnx.org/js-builds/ (I think Jenkins builds this automatically?)
	- [x] cnx-deploy: needs a manual PR opened, reviewed, and merged to update `environments/__prod_envs/vars/versions.yml`
- [x] **cnx-archive** (*Ross*)
 	- [x] Release tag created in GitHub
 	- [x] PyPi version revved
	- [x] cnx-deploy: 2 files need updating (a bot will automatically create this PR, which will need to be reviewed and merged):
		- ` environments/__prod_envs/files/archive-requirements.txt`
		- `environments/__prod_envs/files/publishing-requirements.txt` 
- [x] **cnx-db** (*Ross*)
 	- [x] Release tag created in GitHub
	- [x] PyPi version revved
	- [x] cnx-deploy: 3 files need updating (a bot will automatically create this PR, which will need to be reviewed and merged.):
		- ` environments/__prod_envs/files/archive-requirements.txt`
		- `environments/__prod_envs/files/press-requirements.txt` 
		-  `environments/__prod_envs/files/publishing-requirements.txt`
- [x] **cnx-press** (*Ross*)
 	- [x] Release tag created in GitHub
	- [x] cnx-deploy: `environments/__prod_envs/vars/versions.yml` should be updated -- this PR must be *MANUALLY* created, will need to be reviewed and merged.
- [x] **nebuchadnezzar** (batch publishing client) (*Ross/Bryan*) - *no cnx-deploy change required*
 	- [x] Release tag created in GitHub
	- [x] PyPi version revved
- [x] **cnx-litezip**  (*Ross*)
 	- [x] Release tag created in GitHub
	- [x] PyPi version revved
	- [x] cnx-deploy should be updated for `environments/__prod_envs/files/press-requirements.txt` -- PRs may or may not be automatically generated.
- [x] **cnxml**  (*Ross*)
 	- [x] Release tag created in GitHub
	- [x] PyPi version revved
	- [x] cnx-deploy should be updated for `environments/__prod_envs/files/press-requirements.txt` -- PRs may or may not be automatically generated.
</details>

## Links to DevOps cards:
- [staging](https://trello.com/c/fwCKzb1Z)
- [prod](https://trello.com/c/PaG4va2o/238-cnxbooks-deploy-to-production-servers-for-20180911-release)
