### ISSUE TITLE
Review card for 2018-09-24 CNX Release

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx#17]
## Milestone dates:
- Code freeze (no new features): **2018-09-13**
- Code deployed to staging server: 2018-09-14
- Testing on staging server: 2018-09-17 => 2018-09-21
- RC Review meeting: 2018-09-18
- Code Released to Production: **2018-09-24**

## Link to release report
https://app.zenhub.com/workspace/o/connexions/cnx/reports?report=release&release=5b86c0e87942476dd34ce828

## Repos updated:
- oer.exports v0.63.0
- webview v0.37.0
- cnx-recipes v1.15.0
- nebuchadnezzar 6.0.0
- Products.RhaptosPrint v0.131
- cnx-archive v4.4.0 (for simulations)
- cnx-db v2.4.0 (html abstract regression, batch auth)
- cnx-press v6.0.0 (batch auth)
- cnx-publishing v0.14.1 (cache stuff)
- Rhaptos/Products.CNXPloneSite 0.76.3dev (support email)
- Rhaptos/Products.RhaptosModuleEditor 0.92 (first publish bug)
- Rhaptos/Products.RhaptosModuleStorage 1.3.0 (legacy batch auth)
- Rhaptos/Products.RhaptosSite 1.47 (legacy batch auth) 

## [Demo](https://app.zenhub.com/workspace/o/connexions/cnx/boards?labels=rc%3Ademo&milestones=CNX%20Q3%232018-09-30&releases=5b86c0e87942476dd34ce828&activeFilters=milestones,releases,labels&repos=137909279,132146582,11369603,54509938,47001649,52555418,16184890,69261380,73113116,17912002,49744755,69270352,56601849,96546820,17381641,73112925,4727655,2917192,69508046,22847321,11369724):
*(hyperlink the header above to the filter view for CNX milestone, release, and label: `rc-demo`)*
- click "Demo" above to see issues w/ label `rc:demo`

## Repo Checklist (Books+CNX)
<details>
<summary>Click here to view checklist</summary>
	
- [x] **oer.exports** (*Helene*)
	- [x] https://github.com/Connexions/oer.exports/blob/master/version.txt should match current release
	- [x] Release created in https://github.com/Connexions/oer.exports/releases
	- [x] New RhaptosPrint egg should be built by DevOps (they need the version number)
- [x] **cnx-recipes** (*Helene*)
	- [x] Release created in https://github.com/Connexions/cnx-recipes/releases
	- [x] cnx-deploy: `environments/__prod_envs/files/publishing-requirements.txt` should be updated -- a bot will automatically create this PR, which will need to be reviewed and merged.
- [x] **webview** (*Helene*)
 	- [x] Release created in https://github.com/Connexions/webview/releases
	- [x] Tarball for version needs to be available at https://packages.cnx.org/js-builds/ (I think Jenkins builds this automatically?)
	- [x] cnx-deploy: needs a manual PR opened, reviewed, and merged to update `environments/__prod_envs/vars/versions.yml`
- [x] **cnx-archive** (*Ross*)
 	- [x] Release tag created in GitHub
 	- [x] PyPi version revved
	- [x] cnx-deploy: `environments/__prod_envs/files/publishing-requirements.txt` should be updated -- a bot will automatically create this PR, which will need to be reviewed and merged.
- [x] **cnx-db** (*Ross*)
 	- [x] Release tag created in GitHub
	- [x] PyPi version revved
	- [x] cnx-deploy: 3 files need updating (a bot will automatically create this PR, which will need to be reviewed and merged.):
		- ` environments/__prod_envs/files/archive-requirements.txt`
		- `environments/__prod_envs/files/press-requirements.txt` 
		-  `environments/__prod_envs/files/publishing-requirements.txt`
- [x] **cnx-press** (*Ross*)
 	- [x] Release tag created in GitHub
	- [x] cnx-deploy: `environments/__prod_envs/vars/versions.yml` should be updated -- a bot will automatically create this PR, which will need to be reviewed and merged.
- [x] **cnx-publishing** (*Ross*)
 	- [x] Release tag created in GitHub
	- [x] PyPi version revved
	- [x] cnx-deploy: `environments/__prod_envs/files/publishing-requirements.txt` should be updated -- a bot will automatically create this PR, which will need to be reviewed and merged.
- [x] **nebuchadnezzar** (batch publishing client) (*Dante/Bryan/Ross*) - *no cnx-deploy change required*
 	- [x] Release tag created in GitHub
	- [x] PyPi version revved
- [ ] **Rhaptos/Products.CNXPloneSite** (*Ross*)
 	- [ ] Release tag created in GitHub
	- [x] dist.rhaptos.org updated
	- [x] cnx-deploy: `environments/__prod_envs/files/versions.cfg` should be updated via manual PRs 
- [ ] **Rhaptos/Products.RhaptosModuleEditor** (*Ross*)
 	- [ ] Release tag created in GitHub
	- [x] dist.rhaptos.org updated
	- [x] cnx-deploy: `environments/__prod_envs/files/versions.cfg` should be updated via manual PRs 
- [ ] **Rhaptos/Products.RhaptosModuleStorage** for legacy batch auth (*Ross*)
 	- [ ] Release tag created in GitHub
	- [x] dist.rhaptos.org updated
	- [x] cnx-deploy: `environments/__prod_envs/files/versions.cfg` should be updated via manual PRs 
- [ ] **Rhaptos/Products. RhaptosSite** for legacy batch auth (*Ross*)
 	- [ ] Release tag created in GitHub
	- [x] dist.rhaptos.org updated
	- [x] cnx-deploy: `environments/__prod_envs/files/versions.cfg` should be updated via manual PRs 
</details>

## Links to DevOps cards:
- [staging](https://trello.com/c/J1iFGTBk)
- prod
