### ISSUE TITLE
Review card for 2018-10-08 CNX Release

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx#25]
## Dates
- Code freeze (no new features): **2018-09-14**
- Code deployed to staging server: 2018-09-28
- Testing on staging server: 2018-10-01 => 2018-10-05
- RC Review meeting: 2018-10-02
- Code Released to Production: **2018-10-08**

## Link to release report
https://app.zenhub.com/workspace/o/connexions/webview/reports?report=release&release=5b8eb381aef63a0ac7e7650c

## Repos updated:
- oer.exports
- webview
- cnx-recipes
- Neb
- Press
- cnx archive

## Demo:
*(hyperlink the header above to the filter view for CNX milestone, release, and label: `rc-demo`)*
- 1
- 2

## Repo Checklist (Books+CNX)
- [ ] **oer.exports** (*Helene*)
	- [ ] https://github.com/Connexions/oer.exports/blob/master/version.txt should match current release
	- [ ] Release created in https://github.com/Connexions/oer.exports/releases
	- [ ] New RhaptosPrint egg should be built by DevOps (they need the version number)
- [ ] **cnx-recipes** (*Helene*)
	- [ ] Release created in https://github.com/Connexions/cnx-recipes/releases
	- [ ] cnx-deploy: `environments/__prod_envs/files/publishing-requirements.txt` should be updated -- a bot will automatically create this PR, which will need to be reviewed and merged.
- [ ] **webview** (*Helene*)
 	- [ ] Release created in https://github.com/Connexions/webview/releases
	- [ ] Tarball for version needs to be available at https://packages.cnx.org/js-builds/ (I think Jenkins builds this automatically?)
	- [ ] cnx-deploy: needs a manual PR opened, reviewed, and merged to update `environments/__prod_envs/vars/versions.yml`
- [ ] **nebuchadnezzar** (batch publishing client) (*Dante/Bryan/Ross*) - *no cnx-deploy change required*
 	- [ ] Release tag created in GitHub
	- [ ] PyPi version revved-- a bot will automatically create this PR, which will need to be reviewed and merged.
- [ ] **cnx-press** (*Ross*)
 	- [ ] Release tag created in GitHub
	- [ ] cnx-deploy: `environments/__prod_envs/vars/versions.yml` should be updated -- a bot will automatically create this PR, which will need to be reviewed and merged.
- [ ] more CNX repos here etc. -- full list here: https://github.com/Connexions/cnx/issues/8
- [ ] **cnx-archive** (*Ross*)
 	- [ ] Release tag created in GitHub
 	- [ ] PyPi version revved
	- [ ] cnx-deploy: 2 files need updating (a bot will automatically create this PR, which will need to be reviewed and merged):
		- ` environments/__prod_envs/files/archive-requirements.txt`
		- `environments/__prod_envs/files/publishing-requirements.txt` 
## Links to DevOps cards:
- staging
- prod
